// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handler

import (
	"git.mcontigo.com/safeplay/newsletter-api/pkg/newsletter"
	"git.mcontigo.com/safeplay/newsletter-api/pkg/newsletter/repository"
	"git.mcontigo.com/safeplay/newsletter-api/pkg/newsletter/service"
)

// Injectors from wire.go:

func Build() newsletter.Handler {
	newsletterRepository := repository.Must()
	newsletterService := service.Must(newsletterRepository)
	newsletterHandler := Must(newsletterService)
	return newsletterHandler
}
